version: '3'
services:
  books_service_dev:
    build:
      context: ./src/books_service
      dockerfile: ./Dockerfile
      image: mihiratdocker/library_books_service
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - books_vol:/usr/src/app/
    networks:
      - monorepo_net
  users_service_dev:
    build:
      context: ./src/users_service
      dockerfile: ./Dockerfile
      image: mihiratdocker/library_users_service
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - users_vol:/usr/src/app/
    networks:
      - monorepo_net
  library_service_dev:
    build:
      context: ./src/library_service
      dockerfile: ./Dockerfile
      image: mihiratdocker/library_library_service
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - library_vol:/usr/src/app/
    networks:
      - monorepo_net
  login_service_dev:
    build:
      context: ./src/login_service
      dockerfile: ./Dockerfile
      image: mihiratdocker/library_login_service
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - login_vol:/usr/src/app/
    networks:
      - monorepo_net
      
# volumes:
  # books_vol:
  # users_vol:
  # library_vol:
  # login_vol:

#   nodejs_vol:

networks:
  monorepo_net:
    driver: bridge
