version: '3'
services:
  books_service_test:
    build:
      context: ./src/books-service
      dockerfile: ./Dockerfile
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - books_vol:/usr/src/app/
    networks:
      - monorepo_net
  users_service_test:
    build:
      context: ./src/users-service
      dockerfile: ./Dockerfile
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - users_vol:/usr/src/app/
    networks:
      - monorepo_net
  library_service_test:
    build:
      context: ./src/library-service
      dockerfile: ./Dockerfile
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - library_vol:/usr/src/app/
    networks:
      - monorepo_net
  login_service_test:
    build:
      context: ./src/login-service
      dockerfile: ./Dockerfile
    restart: on-failure
    command: /bin/sh -c 'while true; do sleep 1; done'
    # volumes:
    #   - login_vol:/usr/src/app/
    networks:
      - monorepo_net

#   nodejs_test:
#     build:
#       context: ./nodejs
#       dockerfile: ./Dockerfile
#     restart: on-failure
#     command: /bin/sh -c 'while true; do sleep 1; done'
#     volumes:
#       - nodejs_vol:/usr/src/app/
#       - /usr/src/app/node_modules
#     networks:
#       - monorepo_net

# volumes:
  # books_vol:
  # users_vol:
  # library_vol:
  # login_vol:

#   nodejs_vol:

networks:
  monorepo_net:
    driver: bridge
